#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root   /var/www/html;
    index  index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
                try_files $uri $uri/ =404;
	}

    location /redirect_me {
        return 301 http://cuberule.com/;
    }
}" > /etc/nginx/sites-available/default

service nginx start
