#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get -y install haproxy=1.8.\*
sed -i '/errorfile 504/a listen dizzysnazzy' /etc/haproxy/haproxy.cfg
sed -i '/listen dizzysnazzy/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 1256-web-01 35.196.89.247:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 1256-web-01 35.196.89.247:80 check/a         server 1256-web-02 3.238.171.88:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start
